on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Fetch project source
      - uses: actions/checkout@v2
      - name: semgrep-action
        uses: returntocorp/semgrep-action@v1
